# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  sln: './src/non.sln'

# We only want to kick off indexing runs for Master
trigger: ['master']

# We don't want to build PRs
pr: none

steps:
- task: DotNetCoreCLI@2
  displayName: Build non ($(buildConfiguration))
  inputs:
    command: build
    projects: $(sln)
    arguments: -c $(buildConfiguration)
- task: PowerShell@2
  displayName: Generate SourceBrowser Index
  inputs:
    filePath: 'genindex.ps1'
- task: FtpUpload@2
  displayName: Upload SourceBrowser Index
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'FTP NonConTroll Index'
    rootDirectory: 'bin\index\index'
    filePatterns: '**'
    remoteDirectory: '/site/wwwroot/index'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: true
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Visual Studio Enterprise(5ea88856-cbf8-44e5-8d86-35a35073a080)'
    Action: 'Restart Azure App Service'
    WebAppName: 'non-source'
    SpecifySlotOrASE: true
    ResourceGroupName: 'NonConTroll-SourceBrowser-ResourceGroup'
    Slot: 'staging'
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Visual Studio Enterprise(5ea88856-cbf8-44e5-8d86-35a35073a080)'
    Action: 'Swap Slots'
    WebAppName: 'non-source'
    ResourceGroupName: 'NonConTroll-SourceBrowser-ResourceGroup'
    SourceSlot: 'staging'
