# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  sln: './src/non.sln'
  tests: './src/NonConTroll.Tests/NonConTroll.Tests.csproj'
  samples: './samples/samples.sln'

parameters:
- name:     operatingSystems
  type:     object
  default:
#  - name:     Ubuntu
#    vmImage:  ubuntu-latest
#  - name:     Mac OS
#    vmImage:  macOS-latest
  - name:     Windows
    vmImage:  windows-latest
- name:     configurations
  type:     object
  default:
  - Debug
  - Release

jobs:

- ${{ each c in parameters.configurations }}:
  - ${{ each os in parameters.operatingSystems }}:
    - job:  job${{ os.name }}${{ c }}
      displayName: ${{ c }} (${{ os.name }})
      timeoutInMinutes: 3 # increase if needed
      pool:
        vmImage:  ${{ os.vmImage }}
      steps:
      # HACK: for me, a nuget-restore prior is required...
      - task: NugetToolInstaller@1
      - task: DotNetCoreCLI@2
        inputs:
          command: restore
          projects: $(sln)

      - task: DotNetCoreCLI@2
        displayName: Build NonConTroll (${{ os.name }} ${{ c }})
        inputs:
          command: build
          projects: $(sln)
          arguments: --configuration ${{ c }}
      - task: DotNetCoreCLI@2
        displayName: Run tests (${{ os.name }} ${{ c }})
        inputs:
          command: test
          projects: $(tests)
          arguments: --configuration ${{ c }}
          publishTestResults: true
      # - task: DotNetCoreCLI@2
      #   displayName: Build samples (${{ os.name }} ${{ c }})
      #   inputs:
      #     command: build
      #     projects: $(samples)
      #     arguments: --configuration ${{ c }}
